import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Policy",
	description: "Generated by create next app",
};

export default function Policy() {
	return (
		<>
			<h1 className="text-4xl  font-bold">Polityka prywatności</h1>
			<p className="text-lg">
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
				auctor, nunc nec
			</p>
		</>
	);
}
