import { type Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
	title: "Policy",
	description: "Generated by create next app",
};

export default function PolicyPage() {
	return (
		<>
			<Suspense fallback="Loading...">
				<h1 className="text-4xl  font-bold">Polityka prywatności</h1>
				<p className="text-lg">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit.
					Donec auctor, nunc nec
				</p>
			</Suspense>
		</>
	);
}
